version: '3.8'

services:
  front-end:
    build: 
      context: ./front-end
    ports:
      - "4000:3000"
    volumes:
      - ./front-end:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

