# @format
---
- name: Deploy Kubernates cluster
  hosts: localhost
  remote_user: sejal
  become: false

  tasks:
    # - name: Run the Secreats and Configurations
    #   shell: kubectl apply -f "{{ item }}"
    #   with_fileglob:
    #     - ./../infra/secrets/*.yaml

    - name: Run Kubernetes Deployment files
      shell: /Applications/Docker.app/Contents/Resources/bin/kubectl apply --validate=false -f "{{ item }}"
      with_fileglob:
        - /Users/sejal/Desktop/SPE_Extraction/k8s/*.yaml